server:
  port: 8888
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/MyTest?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username:
        login-password:

logging:
  level:
    root: info
    com.lmt.ecom: debug
    org.springframework.mail: info
    org.springframework.mail.javamail: info
    org.mybatis: info

logstash:
  host: localhost


mybatis-plus:
  mapper-locations: classpath:dao/*.xml



