server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mallProd?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username:
        login-password:
  mail:
    host: smtp.gmail.com
    username:
    password:
    port: 587
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: false

#  data:
#    mongodb:
#      host: mongo
#      port: 27017
#      database: ecom-port

  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6791 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

  rabbitmq:
    host: rabbit
    port: 5672
    virtual-host: /mall
    username:
    password:

  jmx:
    enabled: false
    default-domain: project3

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.lmt.ecom: info

logstash:
  host: logstash


